# Initially generated by 'nixos-generate-config', now the checked-in,
# hand-maintained hardware source of truth for this host -- it is NOT
# regenerated (disko.nix owns the install-time layout). Make changes here
# or in the host's default.nix.
{
  config,
  lib,
  pkgs,
  site,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "thunderbolt"
    "usbhid"
    "uas"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "compress=zstd"
      "noatime"
    ];
  };

  boot.initrd.luks.devices."cryptroot".device =
    "/dev/disk/by-uuid/edd10253-0604-43f8-8662-a54ac2f20232";
  # Process dm-crypt inline (skip the kcryptd workqueues) -- latency/throughput
  # win on this NVMe with zero crypto change (AES-256-XTS + Argon2 unchanged).
  boot.initrd.luks.devices."cryptroot".bypassWorkqueues = true;
  # Pass TRIM through dm-crypt: without this every discard=async and fstrim
  # request dies at the crypt layer (lsblk --discard showed DISC-GRAN 0B).
  # Accepted trade: free-space patterns visible to disk forensics.
  boot.initrd.luks.devices."cryptroot".allowDiscards = true;

  # Declarative machine identity, pinned in the site registry: managed
  # /etc content (the overlay's lower layer) instead of a runtime file
  # that regenerates -- and therefore survives reinstalls. Content matches
  # what systemd wrote at first boot, so adopting the pin is a no-op.
  environment.etc."machine-id" = {
    text = site.hosts.ryzen-9950x3d.machineId + "\n";
    mode = "0444";
  };

  fileSystems."/home" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/var/log" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    # nodatacow: logs are append-only. CoW fragments them + amplifies writes.
    # NOTE: nodatacow also disables compression -- a compress= token on this
    # mount would be inert (btrfs precedence), so none is set.
    # Applies to NEW files after mount — log rotation handles the rest.
    options = [
      "subvol=@log"
      "nodatacow"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/var/cache" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [
      "subvol=@cache"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/var/tmp" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [
      "subvol=@tmp"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/.snapshots" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [
      "subvol=@snapshots"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/95F5-5984";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ]; # Restrict permissions (security fix)
  };

  # Windows SSD (NVMe)
  fileSystems."/mnt/Windows-SSD" = {
    device = "/dev/disk/by-uuid/E434E5EA34E5BFA2";
    fsType = "ntfs3";
    options = [
      "uid=1000"
      "gid=100"
      "dmask=022"
      "fmask=133"
      "noexec"
      "nosuid"
      "nodev"
      "nofail"
      "x-systemd.automount"
    ];
  };

  # Data HDD (SATA)
  fileSystems."/mnt/HDD" = {
    device = "/dev/disk/by-uuid/F0C45ADFC45AA81C";
    fsType = "ntfs3";
    options = [
      "uid=1000"
      "gid=100"
      "dmask=022"
      "fmask=133"
      "noexec"
      "nosuid"
      "nodev"
      "nofail"
      "x-systemd.automount"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
