{ inputs, ... }:
{
  imports = [ inputs.treefmt-nix.flakeModule ];

  perSystem =
    { pkgs, ... }:
    {
      treefmt = {
        projectRootFile = "flake.nix";

        # Exclude auto-generated template files (contain raw option defaults, not valid Nix)
        settings.global.excludes = [
          "docs/*.example"
        ];

        # Nix
        programs.nixfmt.enable = true;
        programs.deadnix = {
          enable = true;
          # Don't flag unused args in lambda attr patterns — flake-parts
          # modules destructure { config, self', inputs', pkgs, … }: and
          # rely on downstream code using a subset.
          no-lambda-pattern-names = true;
          # Don't flag bindings intentionally prefixed with underscore
          # (upcoming `_foo` sentinels; standard nixpkgs convention).
          no-underscore = true;
        };
        programs.statix.enable = true;

        # Shell
        programs.shfmt.enable = true;
        programs.shellcheck.enable = true;

        # JSON, YAML, Markdown
        programs.prettier = {
          enable = true;
          package = pkgs.prettier; # nodePackages removed from nixpkgs; use top-level
          includes = [
            "*.json"
            "*.yaml"
            "*.yml"
            "*.md"
          ];
          excludes = [
            "flake.lock"
            ".ai-context/**"
            "repos/**"
            # Auto-generated by `update-docs` hook. Generator produces its
            # own canonical form; prettier reformatting them causes
            # oscillation with the next regen (treefmt --fail-on-change).
            "docs/options.json"
            "docs/OPTIONS.md"
          ];
        };
      };
    };
}
