{ config, lib, pkgs, modulesPath, ... }:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];
  boot.initrd.availableKernelModules = [ "ehci_hcd" "ehci_pci" "xhci_hcd" "xhci_pci"  "ahci" "usbhid" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  fileSystems."/" = { device = "/dev/disk/by-uuid/06c2c434-c90f-449c-af96-40c17d3626d8"; fsType = "ext4"; };
  boot.initrd.luks.devices."luks-e7f16208-2b7e-4d59-bcee-2519069ad71b".device = "/dev/disk/by-uuid/e7f16208-2b7e-4d59-bcee-2519069ad71b";
  fileSystems."/boot" = { device = "/dev/disk/by-uuid/C9B8-759B"; fsType = "vfat"; options = [ "fmask=0077" "dmask=0077" ]; };
  swapDevices = [ ];
  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

# # /hosts/NixOs-MacBookPro-9-2/hardware-configuration.nix
# # Do not modify this file! It was generated by ‘nixos-generate-config’
# # and may be overwritten by future invocations. Please make changes
# # to /etc/nixos/configuration.nix instead.
# { config, lib, pkgs, modulesPath, ... }:

# {
#   imports =
#     [ (modulesPath + "/installer/scan/not-detected.nix")
#     ];

#   boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "sd_mod" "sdhci_pci" ];
#   boot.initrd.kernelModules = [ ];
#   boot.kernelModules = [ "kvm-intel" ]; #"wl" ]; # Note: 'wl' is Broadcom Wi-Fi, 'kvm-intel' is virtualization. Moved 'kvm-intel' logic to virtualization.nix
#   boot.extraModulePackages = [ ]; # Specific Broadcom Wi-Fi driver

#   fileSystems."/" =
#     { device = "/dev/disk/by-uuid/06c2c434-c90f-449c-af96-40c17d3626d8";
#       fsType = "ext4";
#     };

#   boot.initrd.luks.devices."luks-e7f16208-2b7e-4d59-bcee-2519069ad71b".device = "/dev/disk/by-uuid/e7f16208-2b7e-4d59-bcee-2519069ad71b";

#   fileSystems."/boot" =
#     { device = "/dev/disk/by-uuid/C9B8-759B";
#       fsType = "vfat";
#       options = [ "fmask=0077" "dmask=0077" ];
#     };

#   swapDevices = [ ];

#   # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
#   # (the default) this is the recommended approach. When using systemd-networkd it's
#   # still possible to use this option, but it's recommended to use it in conjunction
#   # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
#   networking.useDHCP = lib.mkDefault true;
#   # networking.interfaces.enp1s0f0.useDHCP = lib.mkDefault true; # Handled by NetworkManager now
#   # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true; # Handled by NetworkManager now

#   nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
#   hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware; # Default, can be overridden in hardware/default.nix
# }