# generate-docs.nix — produce markdown + JSON for every `myModules.*` option.
#
# Pure-nix walker: no derivation build. Eval the flake's options tree and
# render directly to a string via `nix eval --raw`. Previous version used
# `pkgs.nixosOptionsDoc` → `pkgs.runCommand` which forced realisation of
# the full nixpkgs-doc toolchain (bash, coreutils, docbook, etc.) on a
# cold store — 10-20 min with daemon contention.
#
# Cold-eval time on a primed daemon: ~3-5 s. With pre-commit's kill-range,
# even with concurrent evals it stays under ~30 s.
#
# Usage:
#   nix eval --raw .#packages.x86_64-linux.docs-markdown   # → markdown
#   nix eval --json .#packages.x86_64-linux.docs-json      # → options.json
#
# The update-docs hook redirects these into docs/OPTIONS.md and
# docs/options.json.

{
  pkgs ? import <nixpkgs> { },
  flake ? builtins.getFlake (toString ../.),
}:

let
  inherit (pkgs) lib;

  # Merge options from ALL hosts to catch host-specific options that only
  # appear on one configuration (e.g. macbook-only modules excluded from
  # ryzen via exhaustiveness-exclude, or vice versa).
  allConfigs = builtins.attrValues flake.nixosConfigurations;
  mergedOptions = lib.foldl' (acc: cfg: lib.recursiveUpdate acc cfg.options.myModules) { } allConfigs;

  # Walk the `myModules` subtree of the option set. Each leaf is an
  # attribute with `_type == "option"` — its siblings are intermediate
  # nested attrsets.
  isOption = v: lib.isAttrs v && (v._type or "") == "option";

  # Render a type description. Types with `description` attr give a human
  # string; fallback is the type name.
  renderType = t: t.description or t.name or "<unknown>";

  # Render a default value. Functions / literals / derivations get best-
  # effort string coercion; missing default yields "—".
  renderDefault =
    opt:
    if !(opt ? default) then
      "—"
    else if lib.isFunction opt.default then
      "<function>"
    else if lib.isDerivation opt.default then
      "<derivation>"
    else if opt.default == null then
      "null"
    else if lib.isString opt.default then
      "\"${opt.default}\""
    else if lib.isBool opt.default then
      (if opt.default then "true" else "false")
    else if lib.isInt opt.default || lib.isFloat opt.default then
      toString opt.default
    else if lib.isList opt.default then
      "[${lib.concatMapStringsSep " " (x: "\"${toString x}\"") opt.default}]"
    else if lib.isAttrs opt.default then
      (
        let
          hasText = opt.default._type or "" == "literalExpression" || opt.default._type or "" == "literalMD";
        in
        if hasText then opt.default.text else "{ … }"
      )
    else
      "<complex>";

  # Extract a short description string. Handles mdDoc wrappers and plain
  # strings.
  renderDescription =
    opt:
    let
      d = opt.description or "";
    in
    if lib.isString d then
      d
    else if lib.isAttrs d && d ? _type && d ? text then
      d.text
    else
      "";

  # Convert a path (list) to a dotted option name.
  locToPath = loc: lib.concatStringsSep "." loc;

  # Recursively walk an options subtree, emitting markdown for each
  # option leaf under the given path. Order is alphabetical per level.
  renderOptions =
    path: node:
    if isOption node then
      let
        name = locToPath path;
        desc = renderDescription node;
        typ = renderType node.type;
        def = renderDefault node;
      in
      ''
        ### `${name}`

        ${desc}

        - **Type:** `${typ}`
        - **Default:** `${def}`
      ''
    else if lib.isAttrs node then
      lib.concatStringsSep "\n" (map (n: renderOptions (path ++ [ n ]) node.${n}) (lib.attrNames node))
    else
      "";

  # Top-level entry: only the `myModules` subtree, skip everything else.
  myModulesOptions = mergedOptions;
  body = renderOptions [ "myModules" ] myModulesOptions;

  # JSON — mirror structure flat: {path, type, default, description}.
  collectJson =
    path: node:
    if isOption node then
      [
        {
          name = locToPath path;
          type = renderType node.type;
          default = renderDefault node;
          description = renderDescription node;
        }
      ]
    else if lib.isAttrs node then
      lib.concatMap (n: collectJson (path ++ [ n ]) node.${n}) (lib.attrNames node)
    else
      [ ];
  jsonOptions = collectJson [ "myModules" ] myModulesOptions;
in
{
  # Pure string — consumed via `nix eval --raw ..#markdown`.
  markdown = ''
    # Options Reference

    > Auto-generated by `scripts/generate-docs.nix`. Run `bash scripts/update-docs.sh` to regenerate.

    ---

    ${body}
  '';

  # Structured — consumed via `nix eval --json ..#json`.
  json = jsonOptions;
}
