# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to the host's default.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

let
  btrfsOpts = [
    "compress=zstd:1" # zstd:1 — 90% of zstd:3 compression, less CPU on 2C/4T
    "noatime"
    "ssd"
    "discard=async"
    # commit=30 (kernel default). Previously 120: reduced to avoid the
    # "btrfs-transacti blocked >120s → hung_task → journald watchdog" hang
    # cascade. Under libata.force=noncq only ONE I/O outstanding at a time,
    # so big accumulated transactions flush too slowly to meet the 120 s
    # hung_task threshold. 30 s interval = smaller flush batches.
    "commit=30"
  ];
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ehci_pci"
    "ahci"
    "firewire_ohci"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sr_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."cryptroot".device =
    "/dev/disk/by-uuid/0d4eafad-07a3-4404-ad90-301b416bbb53";

  fileSystems."/" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@" ] ++ btrfsOpts;
  };

  fileSystems."/home" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@home" ] ++ btrfsOpts;
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@nix" ] ++ btrfsOpts;
  };

  fileSystems."/var/log" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    # nodatacow disables copy-on-write for log files (append-only workload).
    # CoW fragments append-heavy files + amplifies writes; append-only
    # logs don't need CoW checksums. ~5-10% less SSD writes on /var/log.
    # Applies to NEW files after mount (log rotation gives us that).
    options = [
      "subvol=@log"
      "nodatacow"
    ]
    ++ btrfsOpts;
  };

  fileSystems."/var/cache" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@cache" ] ++ btrfsOpts;
  };

  fileSystems."/tmp" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@tmp" ] ++ btrfsOpts;
  };

  fileSystems."/.snapshots" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@snapshots" ] ++ btrfsOpts;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4827-778F";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
