# Do not modify this file! It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations. Please make changes
# to the host's default.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "firewire_ohci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "b43" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9500b933-62f0-4dd6-8911-6969ec39e57a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-7aa931e6-7038-4b2d-9b62-cbef0f5bf667".device = "/dev/disk/by-uuid/7aa931e6-7038-4b2d-9b62-cbef0f5bf667";
  boot.initrd.luks.devices."luks-fa5e101b-1565-4513-a4da-50b3e9dd808a".device = "/dev/disk/by-uuid/fa5e101b-1565-4513-a4da-50b3e9dd808a";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5ED7-6345";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/758c450c-0e53-413a-8de3-0ec9ce7327bf"; }
    ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
